blank_issues_enabled: true
contact_links:
  - name: Connector Request
    url: https://github.com/wagmi-dev/references/discussions/new?category=connector-request
    about: Kick off a request for a new Connector
